# Generated by Django 5.2.17 on 2026-08-25 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_app_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={'verbose_name': 'Приложение', 'verbose_name_plural': 'Приложение'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категория'},
        ),
    ]
